import { sanitizeForPreview } from "../../utils/sanitize";

interface PreviewProps {
  html: string;
}

export function Preview({ html }: PreviewProps) {
  const safe = sanitizeForPreview(html);
  return (
    <div className="rounded-2xl border border-slate-200/90 bg-slate-50/50 shadow-xs overflow-hidden">
      {/* Mock Browser/Editor Header */}
      <div className="px-4 py-2.5 bg-slate-100/90 border-b border-slate-200/80 flex items-center justify-between">
        <div className="flex items-center gap-1.5">
          <span className="w-2.5 h-2.5 rounded-full bg-rose-400"></span>
          <span className="w-2.5 h-2.5 rounded-full bg-amber-400"></span>
          <span className="w-2.5 h-2.5 rounded-full bg-emerald-400"></span>
          <span className="ml-2 text-xs font-semibold text-slate-500">
            Vista previa en Moodle
          </span>
        </div>
        <span className="text-[11px] font-medium text-slate-400">
          TinyMCE Compatible
        </span>
      </div>

      <div
        className="mcb-preview bg-white p-4 sm:p-6 overflow-auto max-h-[700px] min-h-[300px]"
        // The HTML is generated by our own templates (all user input is
        // escaped) and additionally sanitized with DOMPurify before injection.
        dangerouslySetInnerHTML={{ __html: safe }}
      />
    </div>
  );
}
