import { sanitizeForPreview } from "../../utils/sanitize";

interface PreviewProps {
  html: string;
}

export function Preview({ html }: PreviewProps) {
  const safe = sanitizeForPreview(html);
  return (
    <div
      className="mcb-preview bg-white border border-gray-200 rounded-lg p-5 overflow-auto"
      // The HTML is generated by our own templates (all user input is
      // escaped) and additionally sanitized with DOMPurify before injection.
      dangerouslySetInnerHTML={{ __html: safe }}
    />
  );
}
